---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    tenant: frontend-team
    toolkit.fluxcd.io/tenant: frontend-team
  name: blue
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    tenant: frontend-team
    toolkit.fluxcd.io/tenant: frontend-team
  name: frontend-team
  namespace: blue
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    tenant: frontend-team
    toolkit.fluxcd.io/tenant: frontend-team
  name: frontend-team-reconciler
  namespace: blue
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:blue:reconciler
- kind: ServiceAccount
  name: frontend-team
  namespace: blue
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    tenant: frontend-team
    toolkit.fluxcd.io/tenant: frontend-team
  name: green
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    tenant: frontend-team
    toolkit.fluxcd.io/tenant: frontend-team
  name: frontend-team
  namespace: green
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    tenant: frontend-team
    toolkit.fluxcd.io/tenant: frontend-team
  name: frontend-team-reconciler
  namespace: green
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:green:reconciler
- kind: ServiceAccount
  name: frontend-team
  namespace: green
