---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: ntfy
  namespace: flux-system
spec:
  type: generic
  address: https://ntfy.sh/kindest
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: my-ntfy
spec:
  # inclusionList:
  #   - ".*failed.*"
  providerRef:
    name: ntfy
  # Event severity that triggers this alert (e.g. error events from a failed sync).
  # eventSeverity: error
  # Optionally, filter by resource kinds if you wish to only alert on specific Flux resources.
  eventSources:
    - kind: GitRepository
      name: '*'
      namespace: '*'
    - kind: HelmRelease
      name: '*'
      namespace: '*'
    - kind: Kustomization
      name: '*'
      namespace: '*'