apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: pagerduty
spec:
  type: pagerduty
  address: https://events.pagerduty.com
  channel: <integrationKey>
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: my-service-pagerduty
spec:
  providerRef:
    name: pagerduty
  # Event severity that triggers this alert (e.g. error events from a failed sync).
  eventSeverity: error
  # Optionally, filter by resource kinds if you wish to only alert on specific Flux resources.
  eventSources:
    - kind: GitRepository
      name: '*'
      namespace: '*'
    - kind: HelmRelease
      name: '*'
      namespace: '*'
    - kind: Kustomization
      name: '*'
      namespace: '*'
