apiVersion: v1
kind: Secret
metadata:
  name: rocket-webhook
data:
  token: c2VjcmV0
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: rocket
spec:
  type: rocket
  secretRef:
    name: rocket-webhook
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: flux-failed-execution-rocketchat
spec:
  inclusionList:
    - ".*failed.*"
  providerRef:
    name: rocketchat
  eventSeverity: error
  eventSources:
    - kind: HelmRelease
      name: '*'
      namespace: '*'
    - kind: Kustomization
      name: '*'
      namespace: '*'

