apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: kafka-acl
  namespace: flux-system
spec:
  path: ./terraform
  sourceRef:
    kind: GitRepository
    name: flux-system
  # vars:
  # - name: subject
  #   value: many_cats
  interval: 30s
  approvePlan: "auto"
  storeReadablePlan: human