---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    tenant: backend-team
    toolkit.fluxcd.io/tenant: backend-team
  name: red
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    tenant: backend-team
    toolkit.fluxcd.io/tenant: backend-team
  name: backend-team
  namespace: red
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    tenant: backend-team
    toolkit.fluxcd.io/tenant: backend-team
  name: backend-team-reconciler
  namespace: red
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:red:reconciler
- kind: ServiceAccount
  name: backend-team
  namespace: red
